<?php
    $product_view = $this->getConfig('porto_settings/product');
    $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
    if($block) {
        $block->setBlockId($product_view['side_custom_block']);
    }
    if($block){
        echo $block->toHtml();
    }
?>

<style>
.columns .column.main {
    width: 50%;
    padding-left: 2%;
}
.left-side-content {
    width: 23%;
    float: left;
}
.sidebar.sidebar-main {
    display: none;
}
</style>