<?php 

/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_CsMarketplace
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (http://cedcommerce.com/)
 * @license     http://cedcommerce.com/license-agreement.txt
 */
?>

<!-- /.navbar-header -->

<ul class="nav navbar-top-links navbar-right in" id="cedheaderitems" data-bind="scope:'cedheaderitems'">
	<?php echo $block->getChildHtml('sidebar'); ?>

	<!-- ko template: getTemplate() -->
	    <li class="dropdown" databind="if : customData.contentLoading(),blockLoader: customData.contentLoading()"></li>
	<!-- /ko -->
	
    <script type="text/x-magento-init">
    {
        "#cedheaderitems": {
            "Magento_Ui/js/core/app": {
               "components": {
                    "cedheaderitems": {
                        "component": "Ced_CsMarketplace/js/view/header",
                        "template" : "Ced_CsMarketplace/headeritems",
                        "url" : "<?= $this->getUrl('csmarketplace/vendor/navigation') ?>",
                        "viewall" : "<?= $this->getUrl('csmarketplace/vendor/notifications') ?>"
                    }
                }
            }
        }
    }
    </script>
	<!-- /.dropdown -->
	
	
	<!-- /.dropdown -->
</ul>
<style>
li#vendor_product_attribute {
    display: none;
}
.navbar-top-links > li > a > span.label{
    font-size: 9px !important;
    line-height: 0.9;
    padding: 2px 3px;
    position: absolute;
    right: 22px;
    text-align: center;
    top: 10px;
}
nav.navbar-default.navbar-static-top 
{
    background: #171717!important;
	}
	.ced-vendor-sidebar-nav .side-menu > li.nav > a {
    color: #F26C4F !important;
}
nav.navbar-default.navbar-static-top, .page-wrapper .panel-default .panel-heading, .ced-vendor-sidebar-nav .side-menu a.active, .nav > li > a:focus {
    background-color: #171717!important;
	}
	.nav > li > a:hover {
    background-color: #171717!important;
}
.slide .side-menu li .nav-second-level li a, .ced-vendor-sidebar-nav .side-menu li .nav-second-level li a.active, .nav-second-level > li > a, .nav-third-level > li > a {
    background: #F26C4F!important;
    color: #fff!important;
}
.ced-vendor-sidebar-nav .side-menu li .nav-second-level li a.active:hover, .nav.nav-second-level > li > a:hover, .nav.nav-third-level > li > a:hover {
    background: #171717!important;
    color: #fff;
}
.for_print_order_button .box-title, .for_print_order_button .order-info, .csmarketplace-vpayments-view .fieldset h2, .dropdown-menu .top-lis a:hover {
    background: #171717!important;
}
ul.dropdown-menu.dropdown-user li a {
  color: #F26C4F!important;
}
.dropdown-tasks .top-lis .progress .progress-bar {
    background: #F26C4F!important;
}
.abs-action-primary, button.primary, .page-actions > button.action-primary, .page-actions .page-actions-buttons > button.action-primary, .page-actions > button.primary, .page-actions .page-actions-buttons > button.primary, .block-footer .action-add.primary, .page-actions > .block-footer .action-add.action-primary, .page-actions .page-actions-buttons > .block-footer .action-add.action-primary, .page-actions > .block-footer .action-add.primary, .page-actions .page-actions-buttons > .block-footer .action-add.primary {
    background-color: #F26C4F !important;
    border-color: #F26C4F!important;
}
.admin__collapsible-block-wrapper .admin__collapsible-title {
    background-color: #F26C4F !important;
}
</style>

<script type="text/javascript">


	var childLis = document.getElementsByClassName("dropdown-tasks");
	if(childLis && childLis[0] && childLis[0].childNodes && childLis.length > 0) {
		childLis = childLis[0].childNodes;
		var lisCnt = 0;
		for(var i=0; i<childLis.length ; i++){
			if(childLis[i].innerHTML != undefined && childLis[i].innerHTML != ''){
				lisCnt++;
			}
		}
		if(lisCnt > 0){
			var labelElement = document.getElementById('dropdown-tasks-label');
			if(labelElement){
				labelElement.innerHTML = lisCnt;
			}
		}
	}

	var childLis = document.getElementsByClassName("dropdown-alerts");
	if(childLis && childLis[0] && childLis[0].childNodes && childLis.length > 0) {
		childLis = childLis[0].childNodes;
		var lisCnt = 0;
		for(var i=0; i<childLis.length ; i++){
			if(childLis[i].innerHTML != undefined && childLis[i].innerHTML != ''){
				lisCnt++;
			}
		}
		if(lisCnt > 0){
			var labelElement = document.getElementById('dropdown-alerts-label');
			if(labelElement){
				labelElement.innerHTML = lisCnt;
			}
		}
	}
	
</script>


