<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<h2 class="item-location-title">Item Location:</h2>
<!-- <div class="locationRadios">
  <div class="anywhereRadio" style="display: flex;align-items: center;">
    <input type="radio" name="anywhere" value="60" selected="true"  label="Anywhere"><span> Anywhere</span>
  </div>
  <div class="withinRadio" style="display: flex;align-items: center;">
    <input type="radio" name="within" value="100"  label="Within"><span> Within</span> 
   </div>
</div> -->

<div class="locationRadios owl-carousel  owl-theme owl-loaded owl-drag">
  <div class="owl-controls">
    <div class="owl-nav disabled">
      <div class="owl-prev">
        <em class="porto-icon-left-open-huge"></em>
      </div>
      <div class="owl-next">
        <em class="porto-icon-right-open-huge"></em>
      </div>
    </div>
    <div class="owl-dots" style="display: flex;flex-direction: column;">
     <!-- <div class="owl-dot active" id="item-anywhere" style="display: flex;">
        <span style="margin: 0 5px 2px 0;border-color: #f26c4f;width: 18px;height: 18px;"></span><div>Anywhere</div>
      </div>
	  -->
	  <div class="owl-dot active" id="item-within" style="display: flex;">
        <span style="margin: 0 5px 2px 0;border-color: #f26c4f;width: 18px;height: 18px;"></span><div>Within</div>
      </div> 
      
    </div>
  </div>
</div>

<div class="block block-search">
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
        <form class="form minisearch" id="location_search_mini_form" action="<?php /* @escapeNotVerified */ echo $block->getUrl('marketplace/seller/allseller/', ['_secure' => $block->getRequest()->isSecure()]); ?>" method="get">
            <div class="field search location-search-field">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control location-control">
                     <select name="distances" id="distances">
                      <option value="all">ALL</option>
                      <option value="5">5 Miles of</option>
                      <option value="10">10 Miles of</option>
                      <option value="25">25 Miles of</option>
                      <option value="50">50 Miles of</option>
                      <option value="100">100 Miles of</option>
                      <option value="250">250 Miles of</option>
                    </select>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
             <div class="field search location-search-field">
                <label class="label" for="search" data-role="minisearch-label">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </label>
                <div class="control location-control">
                    <input id="locationSearch"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#location_search_mini_form",
                                "url":"<?php /* @escapeNotVerified */ echo $block->getUrl('marketplace/seller/allseller/', ['_secure' => $block->getRequest()->isSecure()]); ?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="number"
                           name="locationSearch"
                           placeholder="<?php /* @escapeNotVerified */ echo __('Zipcode...'); ?>"
                           class="input-text"
                           maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?php echo $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                        title="<?php echo $block->escapeHtml(__('Search')) ?>"
                        class="action search" id="locationSearchAction">
                    <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                </button>
            </div>
        </form>
    </div>
</div>
<hr style="border-top-width: 5px; margin-top: 10%;">

<style type="text/css">

  .block-search {

    margin-left: 0;
    width: 100%;

  }

  .block-search input {

    background-color: #eee;
    border: none;

  }
  
  .block-search input:focus {

    box-shadow: none;

  }

  .block-search .action.search {

    background-color: #f26c4f;
    width: 20%;
    color: #fff;
    margin-right: -1px;

  }

  .block-search .action.search:hover {

    background-color: #f26c4f;
    width: 20%;
    color: #fff;
    margin-right: -1px;

  }

  .block-search .action.search::before {

    color: #fff;

  }

  .locationRadios {

    margin-bottom: 3%;

  }

  .locationRadios span:after {

    background-color: #f26c4f!important;

  }

  .location-search-field {

    width: 40%!important;

  }

  .location-control {

    border: 1px solid #ddd!important;
    border-right: none!important;
    height: 100%;

  }

  .item-location-title {

    color: black;
    font-weight: 550;
    font-size: large;


  }

  #location_search_mini_form {

    display: flex;


  }

  #locationSearch {

    padding: 5px 15px 5px 15px;
    background-color: #fff!important;
    height: 38px;
  }

  #distances {

    padding: 5px 10px 5px 10px;
    height: 100%;
    background-color: #fff;
    border: none;

  }

  #distances:focus {

    box-shadow: none;

  }

  #locationSearchAction {

    border: 1px solid #aaa;

  }

  #locationSearchAction:before {

    content: 'GO';

  }
  .block-search .action.search:focus, .block-search .action.search:active {

    background-color: : #f26c4f;

  }
  .block-search .action.search:focus, .block-search .action.search:active {
    background-color: #f26c4f;
    border: none;
}
</style>
