<?php
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Auction
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */

?>

    <div class="admin__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ $block->getHeaderText() ?></span>
        <?php if($block->getButtonsHtml()): ?>
            <div class="actions"><?= $block->getButtonsHtml() ?></div>
        <?php endif; ?>
    </div>

<?= $block->getChildHtml('', true) ?>