<?php
/** CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_GiftCard
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */ 
/*
* Note: initially, after clicking loadmore action
* Block file : Ced\Custom\Block\Product\Loadmore\Interceptor
*/
 
// @codingStandardsIgnoreFile

?> 


<div class="gift-wrapper-mail">
    <div class="gift-image-wrapper">
        <img src="#" alt="" id="gallery-image" align="center" border="0" style="margin: auto;" class="fluid">
    </div>
    <div class="gift-card-details">
        <div class="clearfix">
            <div class="left">
                <img id="gallery_gift_storelogo" alt="Store_Logo" src="#" width="170" height="54">
            </div>
            <div class="right">
                <div class="price-details">
                    <span id="gallery-gift-currencysymbol"></span>
                    <span id="gallery-gift-amount">00.00</span>
                </div> 
            </div>
        </div>
        <div class="messages-wrapper">
            <span id="gallery_gift_message" class="message"><?php echo __('Message will show here ') ?></span>
        </div>
        <div class="preview">
            <label class="gift_preview_link" for="preview"><?php echo __('Click Here  For Preview') ?></label>
            <div id="gift_preview_html" class="gift_preview_html">
                <div id="child_gift_preview_html" class="child_gift_preview_html">

                </div>
            </div>
        </div>
    </div>
</div> 