<?php
/** CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_GiftCard
 * @author      CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license     https://cedcommerce.com/license-agreement.txt
 */

// @codingStandardsIgnoreFile

?>
 <?php $post = $block->getPostValue(); ?>

<?php
    $iamge = isset($post['image'])?$post['image']:'';
    $post['gift_from_name'] = ($post['gift_from_name'])?($post['gift_from_name']): __('Someone');
    $post['image_label'] = ($post['image_label'])?($post['image_label']): __('Gift Card');
?>
<div class="modal-close">X</div>
<div class="gift-card-details wrapper">
    <!--@subject {{var gift_from_name}} sent you an {{var image_label}} @-->
    <style>
        @media screen and (max-width: 599px) {
            .table-wrapper {
                width: 100%;
            }
            .td-width {
                width: 100%;
            }
            .hide-table {
                display: none;
            }
        }
        @media screen and (max-width: 340px) {
            .res-td {
                padding: 0;
            }
        }
    </style>
    <body style="padding: 0; margin: 0;">
    <table class="table-wrapper" align="center" border="0" cellpadding="0" cellspacing="0" width="600" style="border-collapse: collapse; font-family: arial; font-size: 14px;">
        <tr>
            <td bgcolor="#f3f3f3" style="padding: 20px 40px 20px 40px; border-bottom: 1px solid #ddd;">
                <table cellspacing="0" cellpadding="0" width="100%">
                    <tr>
                        <td style="font-weight: bold; padding-bottom: 20px;">
                            <?php echo __('Gift card sent to:') ?> <?php echo isset($post['gift_to_name'])?$post['gift_to_name']:' ' ?>
                        </td>
                    </tr>
                    <tr>
                        <td style="font-weight: bold; padding-bottom: 5px;">
                            <?php echo __('Subject:') ?>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <?php echo  __('%1 sent you a %2', $post['gift_from_name'], $post['image_label'])?>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td class="res-td" bgcolor="#ffffff" style="padding: 20px 40px 20px 40px;">
                <table cellspacing="0" cellpadding="0" width="100%">
                    <tr>
                        <td style="border: 1px solid #ddd;">
                            <table cellspacing="0" cellpadding="0" width="100%">
                                <tr>
                                    <td align="center">
                                        <a href="#" style="display: block;">
                                            <img src="<?php echo (isset($iamge)? $iamge:' ') ?>" alt="alt text" width="100%">
                                        </a>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="padding: 20px 20px 10px 20px;">
                                        <table class="td-width mobile-full" cellspacing="0" cellpadding="0" valign="top" align="left" style="" width="210px">
                                            <tr>
                                                <td align="center" style="padding-bottom: 20px;">
                                                    <a class="logo" href="{{store url=""}}">
                                                    <img
                                                            width="180"
                                                            alt="<?php echo $block->getLogoAlt() ?>"
                                                            src="<?php echo $block->getLogoSrc() ?>"
                                                            border="0"
                                                            width="100%"
                                                    />
                                                    </a>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="color: #8E8E8E;">
                                                    <?php echo __('Gift Card Id:') ?>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="color: #8E8E8E; font-weight: bold; padding-bottom: 20px;">
                                                    XXXXXXXXXXXXXXXX
                                                </td>
                                            </tr>
                                        </table>

                                        <table class="hide-table mobile-hide"  align="left" style="border-right: 1px solid #ddd; height: 180px; width: 10px;">
                                            <tr>
                                                <td style="display: block"></td>
                                            </tr>
                                        </table>

                                        <table class="td-width mobile-full" cellspacing="0" cellpadding="0" valign="top" align="left" width="210px">
                                            <tr>
                                                <td align="center" style="padding-bottom: 20px; font-size: 25px; color: #333333;">
													<span>

														<?php echo $block->getStoreCurrency().' '.(isset($post['gift_price'])?$post['gift_price']:00.00) ?>
													</span>
                                                </td>
                                            </tr>
                                            <tr>
                                                <td align="center" style="color: #8E8E8E; padding-bottom: 20px;">
                                                    <?php echo __('Expires') ?>: dd/mm/yyyy
                                                </td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="height: 50px; border-top: 1px solid #dddddd;">
                                        <p style="padding:20px 40px 20px 40px">
                                            <?php echo isset($post['gift_message'])?$post['gift_message']:' ' ?>
                                        </p>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    </body>
</div>
<?php die; ?>