<?php
$porto_helper = $this->helper('Smartwave\Porto\Helper\Data');
?>
<li><a href="<?php echo $porto_helper->getBaseLinkUrl(); ?>contact"><?php echo __('Contact Us'); ?></a></li>

<!-- <li><a href="<?php echo $porto_helper->getBaseLinkUrl(); ?>about-porto-nowauction"><?php echo __('About us'); ?></a></li>-->
<!-- <li><a href="<?php // echo $porto_helper->getBaseLinkUrl(); ?>marketplace/seller/allseller/"><?php echo __('Stores'); ?></a></li> -->
<!-- <li><a href="<?php // echo $porto_helper->getBaseLinkUrl(); ?>mynowauctions"><?php echo __('My Nowauctions'); ?></a></li> -->
<!-- <li style="margin-right: 8px; width: 190px;"><?php // echo $this->getChildHtml("left.side.search"); ?></li> -->
<!-- <li style="margin-right: 8px;"> <?php // echo $this->getChildHtml("minicart"); ?></li> -->
<style>
.page-header.type13:not(.header-newskin) .panel.header .links > li {

    vertical-align: inherit!important;

}
.page-header.type13:not(.header-newskin) .panel.header .top-links-area > ul.links > li > a {
 
    margin-right: 10px;

}
.page-header .control input {
    height: 30px!important;
}
.page-header .actions button {
    height: 30px!important;
}
.page-header .actions button:before {
    line-height: 30px!important;
}

.page-header.type13:not(.header-newskin) .minicart-wrapper .action.showcart::before {

    content: '\f87a';
    color: #ff5501;
    font-size: 25px;
    line-height: 1;

}

.page-header.type13:not(.header-newskin) .minicart-wrapper .action.showcart .counter.qty {

    color: #fff;
    background: #ff5501;
    border-radius: 8px;
    width: 15px;
    height: 15px;
    line-height: 15px;
    font-size: 11px;
    position: absolute;
    top: auto;
    right: -7px;
    bottom: -7px;
    margin: 0;
    padding: 0;
    left: auto;
    display: block;
    min-width: 0;

}
.page-header.type13:not(.header-newskin) .minicart-wrapper .action.showcart.active::before {

    color: #ff5501;

}
.header.links .block-search {
    overflow: hidden;
}
</style>