<!--
/**
 * CedCommerce
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End User License Agreement (EULA)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://cedcommerce.com/license-agreement.txt
 *
 * @category    Ced
 * @package     Ced_Auction
 * @author 		CedCommerce Core Team <connect@cedcommerce.com>
 * @copyright   Copyright CedCommerce (https://cedcommerce.com/)
 * @license      https://cedcommerce.com/license-agreement.txt
 */
-->
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
 
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 
//echo $storeManager->getStore()->getStoreId() . '<br />'; 
//echo $storeManager->getStore()->getCode() . '<br />'; 
//echo $storeManager->getStore()->getName() . '<br />'; 
//echo $storeManager->getStore()->getStoreUrl() . '<br />';
//echo $storeManager->getStore()->getWebsiteId() . '<br />';

?>


<div class="page-title-wrapper">
    <h1 class="page-title">
        <span data-ui-id="page-title-wrapper" class="base">Product List</span>
    </h1>
</div>
<div class="products wrapper grid products-grid">
    <ol class="products list items product-items auction-list row">
        <?php
        $timezone = $block->getTimeZone()->getConfigTimezone();
        $auctionDetails = $block->getAuctionProduct();
		
		$vendors = $block->getLoadedVendorCollection();
	
	
        $block->updateClosedAuction();
        $enableAuction = $block->getAuctionEnable();
        if ($enableAuction && $auctionDetails) {
			//var_dump($auctionDetails->getdata()); 
        foreach ($auctionDetails as $detail) {
            $block->changeStatus();
            $productId = $detail->getProductId();
            $startTime = $detail->getStartDatetime();
            $endTime = $detail->getEndDatetime();
            $url = $block->getAuctionProductUrl($productId);
			
		$VendorId = $detail->getVendorId();

			
	
			
				 $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
    $storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
    $currencyCode = $storeManager->getStore()->getCurrentCurrencyCode(); 
    $currency = $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode); 
 $currencySymbol = $currency->getCurrencySymbol(); 
	
$productCollection = $objectManager->create('Magento\Catalog\Model\Product')->load($productId);
$productPriceById = $productCollection->getPrice();

			$status = $detail->getStatus();
			$reservedAmount = $detail->getStartingPrice();
			$productStartingAmount = $detail->getMaxPrice();
			$productPrice = $productPriceById;
			 $prdouctTime = $productStartingAmount - $reservedAmount;
			 $finalTime =  $prdouctTime * 100;
			$finalDate =  date("m-d-Y H:i:s", strtotime($startTime) + $finalTime);
				

            if ($url) {
                if ($detail->getStatus() == 'not started') {
                    $countDownTime = $startTime;
                    ?>

     <li class="item product product-item col-xl-3 col-lg-4 col-md-4 col-sm-6 col-6 upcoming_auction all-auctions"  data-product="<?= $productId; ?>"
             data-counter="<?= $countDownTime; ?>" data-price="<?= $productStartingAmount; ?>" data-status="<?= $status; ?>" data-finaltime="<?= $finalTime; ?>">
                        <div class="product-item-info" data-container="product-grid">

                            <a href="<?php if ($block->getAuctionProductUrl($productId)) {
                                echo $block->getAuctionProductUrl($productId);
                            } ?>"
                               class="product photo product-item-photo" tabindex="-1">
                                <?php $image = $block->getImage($block->getProduct($productId), 'category_page_list'); ?>
                                <?php if ($image) {
                                    echo $image->toHtml();
                                } ?>
                            </a>
           <div class="product details product-item-details">
                                <input type="hidden" value="1">
                                <strong class="product name product-item-name">


                                    <a class="ced_product-item-link"
                                       href="<?php if ($block->getAuctionProductUrl($productId)) {
                                           echo $block->getAuctionProductUrl($productId);
                                       } ?>">
                                        <?php if ($detail->getProductName()) {
                                            echo $detail->getProductName();
                                        } ?>
                                    </a>
                                </strong>
							
                                        <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($productCollection); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                           
                                        </div>
								 <div class="related-starting-bid" bis_skin_checked="1">
												<label>Sale Price</label>
												<span>
												   <?php 
												   $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
													$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
													$price =  $productCollection->getPrice();
													echo $priceHelper->currency($price, true, false);
																   ?>         </span>
											</div>
									
                               
<button  style="margin:10px 0 0px 0px;" type="submit"
											   title="BUY NOW"
											   class="action tocart primary">
											   <span>Buy <span style="color: #F26C4F;font-style: italic;font-size: 15px;">Now</span></span>
										</button>
                             
								    <button class="action tocart primary"
                                        onclick="window.location.href='<?= $url ?>'">
										Bid <span style="color: #F26C4F;font-style: italic;font-size: 15px;">Now</span>
                                </button>
								
								 <button class="action tobidcart primary"
                                        onclick="window.location.href='<?= $url ?>'">
										Submit Bid
                                </button>
								
								
							<?php
							
								$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
								$addToCartUrl =  $listBlock->getAddToCartUrl($productCollection);
								?>
								<form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
									<?php echo $block->getBlockHtml('formkey')?>
									   
								 </form>
          </div>
		  <div class="start-price-box">
		   <div class="price-box price-final_price">                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                    
                                    <span class="price-wrapper ">
                                                            <span class="price"><?= __('Starts at:') ?></span>
                                                 </span>



                                    <div id="countdown_timer" class="auction_timer">
                                        
											 
											 <?php
											 echo "$startTime";  
											 echo "<br>";
										
											 ?>
											 
				
                                       
                                    </div>
                                </div>
								</div>
                        </div>
						<div class="delivery-sec">
				<?php
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
					?>
				<img src="<?php echo $mediaUrl;?>delivery_img.png">
			</div>
                    </li>
                    <?php
                } ?>
                    <?php
                if ($detail->getStatus() == 'processing') {
							
				
				$addCls ='';
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
					$connection = $resource->getConnection();
					$tableName = $resource->getTableName('ced_auction_biddetails');

					//Select Data from table
					$sql = "Select * FROM " . $tableName."  WHERE product_id = " . $productId;
					$results = $connection->fetchAll($sql);
					//echo "<pre>";print_r($results);
					$countStatus = array();
					foreach ($results as $key => $data)
					 {
					  if ($data['status'] == 'bidding') 
					  {
						 if ($data['product_id'] == $productId) 
						 { 
						 $addCls = "trending_auction featured_auction";		
				 
						 }			
						}
					 }
		
		
		
                   // $countDownTime = $endTime;
					$countDownTime = $finalDate;
			
                    ?>
                   <li class="item product product-item col-xl-3 col-lg-4 col-md-4 col-sm-6 col-6 live_auction all-auctions <?php echo $addCls;?>" data-product="<?= $productId; ?>"
                        data-counter="<?= $countDownTime; ?>" data-price="<?= $productStartingAmount; ?>" data-status="<?= $status; ?>" data-finaltime="<?= $finalTime; ?>">
                        <div class="product-item-info" data-container="product-grid">

                           <a
                                    href="<?php if ($block->getAuctionProductUrl($productId)) {
                                        echo $block->getAuctionProductUrl($productId);
                                    } ?>"
                                    class="product photo product-item-photo" tabindex="-1">
                                <?php $image = $block->getImage($block->getProduct($productId), 'category_page_list'); ?>
                                <?php if ($image) {
                                    echo $image->toHtml();
                                } ?>
                            </a>
                            <div class="product details product-item-details">
                                <input type="hidden" value="1">
                                <strong class="product name product-item-name">


                                    <a class="ced_product-item-link"
                                       href="<?php if ($block->getAuctionProductUrl($productId)) {
                                           echo $block->getAuctionProductUrl($productId);
                                       } ?>">
                                        <?php if ($detail->getProductName()) {
                                            echo $detail->getProductName();
                                        } ?></a>
                                </strong>
								         <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($productCollection); ?>'  class="action towishlist" data-action="add-to-wishlist" title="<?php /* @escapeNotVerified */ echo __('Add to Wish List') ?>">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                           
                                        </div>
 <div class="related-starting-bid" bis_skin_checked="1">
                <label>Sale Price</label>
                <span>
                   <?php 
				   $objectManager = \Magento\Framework\App\ObjectManager::getInstance(); // Instance of Object Manager
					$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
					$price =  $productCollection->getPrice();
					echo $priceHelper->currency($price, true, false);
								   ?>         </span>
            </div>
						
						

                                <div class="price-box price-final_price">
                                  <?php
							
								$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
								$addToCartUrl =  $listBlock->getAddToCartUrl($productCollection);
								?>
								<form data-role="tocart-form" action="<?php echo $addToCartUrl; ?>" method="post">
									<?php echo $block->getBlockHtml('formkey')?>
									   <button  style="margin-top:0px;" type="submit"
											   title="BUY NOW"
											   class="action tocart primary">
											   <span>Buy <span style="color: #F26C4F;font-style: italic;font-size: 15px;">Now</span></span>
										</button>
								 </form><div class="auc_price">
								 <span id="aPrice_<?php if ($productId) {
                                                 echo $productId;
                                             } ?>" style="    color: #F26C4F;
    font-size: 17px;
    font-weight: bold;
    padding: 0px 0;
    line-height: 28px;"></span>
								  </div>

                                    <span class="price-wrapper ">
                                                            <span class="price"><?php // __('Time left:') ?></span>
                                            </span>

                                    <div id="countdown_timer" class="auction_timer" style="display:none;">
									<a class="ced_product-item-link"
                                       href="<?php if ($block->getAuctionProductUrl($productId)) {
                                           echo $block->getAuctionProductUrl($productId);
                                       } ?>">
                                    
                                        <div class="auction_timer_days"
                                             id="auction_days_<?php if ($productId) {
                                                 echo $productId;
                                             } ?>"></div>
                                        <div class="auction_timer_hours"
                                             id="auction_hours_<?php if ($productId) {
                                                 echo $productId;
                                             } ?>"></div>
                                        <div class="auction_timer_minutes"
                                             id="auction_minutes_<?php if ($productId) {
                                                 echo $productId;
                                             } ?>"></div>
                                        <div class="auction_timer_seconds"
                                             id="auction_seconds_<?php if ($productId) {
                                                 echo $productId;
                                             } ?>"></div>
                                    </div>
									</a>
                                </div>

                                <button class="action tocart primary"
                                        onclick="window.location.href='<?= $url ?>'">
										Bid <span style="color: #F26C4F;font-style: italic;font-size: 15px;">Now</span>
                                </button>
								
								 <button class="action tobidcart primary"
                                        onclick="window.location.href='<?= $url ?>'">
										Submit Bid
                                </button>
							
                            </div>
							<div class="start-price-box">
							<span>Auction is Live <span style="color: #F26C4F;font-style: italic;font-size: 15px;">Now</span></span>
							
							
							</div>
                        </div>
						<div class="delivery-sec">
				<?php
				$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$mediaUrl = $objectManager->get('Magento\Store\Model\StoreManagerInterface')
                    ->getStore()
                    ->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
					?>
				<img src="<?php echo $mediaUrl;?>delivery_img.png">
			</div>
                    </li>

                    <?php
                } ?>

                    <?php
                if ($detail->getStatus() == 'closed') { ?>
                    <li class="item product product-item col-xl-3 col-lg-4 col-md-4 col-sm-6 col-6 closed_auction all-auctions" data-product="<?= $productId; ?>">
                        <div class="product-item-info" data-container="product-grid">

                            <a href="<?= $block->getAuctionProductUrl($productId) ?>"
                               class="product photo product-item-photo" tabindex="-1">
                                <?php $image = $block->getImage($block->getProduct($productId), 'category_page_list'); ?>
                                <?php if ($image) {
                                    echo $image->toHtml();
                                } ?>
                            </a>
                            <div class="product details product-item-details">
                                <input type="hidden" value="1">
                                <strong class="product name product-item-name">


                                    <a class="ced_product-item-link"
                                       href="<?php if ($block->getAuctionProductUrl($productId)) {
                                           echo $block->getAuctionProductUrl($productId);
                                       } ?>">
                                        <?php if ($detail->getProductName()) {
                                            echo $detail->getProductName();
                                        } ?></a>
                                </strong>

                                <button class="action tocart primary"><?= __('Bidding closed') ?>
                                </button>
                            </div>
                        </div>
                    </li>
                    <?php
                } ?>

                    <?php
                if ($detail->getStatus() == 'cancelled') { ?>
                    <li class="item product product-item col-xl-3 col-lg-4 col-md-4 col-sm-6 col-6 cancel_auction all-auctions" data-product="<?= $productId; ?>">
                        <div class="product-item-info" data-container="product-grid">

                            <a href="<?php if ($block->getAuctionProductUrl($productId)) {
                                echo $block->getAuctionProductUrl($productId);
                            } ?>"
                               class="product photo product-item-photo" tabindex="-1">
                                <?php $image = $block->getImage($block->getProduct($productId), 'category_page_list'); ?>
                                <?php if ($image) {
                                    echo $image->toHtml();
                                } ?>
                            </a>
                            <div class="product details product-item-details">
                                <input type="hidden" value="1">
                                <strong class="product name product-item-name">


                                    <a class="ced_product-item-link"
                                       href="<?php if ($block->getAuctionProductUrl($productId)) {
                                           echo $block->getAuctionProductUrl($productId);
                                       } ?>">
                                        <?php if ($detail->getProductName()) {
                                            echo $detail->getProductName();
                                        } ?></a>
                                </strong>

                                <button class="action tocart primary"><?= __('Bidding cancelled') ?>
                                </button>
                            </div>
                        </div>
                    </li>
                <?php
                }
            }
        } ?>

            <script>
                require(['jquery', 'jquery/ui'], function ($) {
                    $(document).ready(function () {
                        let timezone = '<?= $timezone ?>';
                        console.log('time');
                        console.log(timezone);

                        $('.product-item').each(function (index, value) {
                            console.log(index);
                            console.log(value);
                            let counter = $(this).data('counter');
                            let product = $(this).data('product');
                            let price = $(this).data('price');
                            let status = $(this).data('status');
                            let finalTime = $(this).data('finaltime');
							 if (product !== undefined && product !== null && counter !== undefined && counter !== null)
                                runTimer(counter, product, price, status, finalTime);
                        });

                        function runTimer($countDownTime, productid, price, status, finalTime) {
                            var countDownDate = new Date($countDownTime).getTime();

                            var x = setInterval(function () {
                                let currLocalTime = new Date().toLocaleString("en-US", {timeZone: timezone});
                                let currentLocalTime = new Date(currLocalTime);
                                console.log('Current ' + timezone + ' time: ' + currentLocalTime.toLocaleString());


                                let now = currentLocalTime.getTime();
									
                                var distance = countDownDate - now;
								console.log("dist is "+countDownDate);
								console.log("curent time  is "+now);
                                var days = Math.floor(distance / (1000 * 60 * 60 * 24));
                                var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                                var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                                var seconds = Math.floor((distance % (1000 * 60)) / 1000);
                                //var productid = $productId;

                                console.log(document.getElementById("auction_days_" + productid));
                                document.getElementById("auction_days_" + productid).innerHTML = days + "d: ";
                                document.getElementById("auction_hours_" + productid).innerHTML = hours + "h: ";
                                document.getElementById("auction_minutes_" + productid).innerHTML = minutes + "m: ";
                                document.getElementById("auction_seconds_" + productid).innerHTML = seconds + "s ";
								
								
								var stattus = status;
							
							if(stattus == "processing")
							{
								var mainDif = finalTime;
								var remainDif = distance / 1000;
								var diff1 = mainDif - remainDif;
								var diff2 = diff1 / 100;
								var productPrice = price;
								var finalProductPrice = productPrice - diff2;												
								var finalProductPrice =finalProductPrice.toFixed(2);
								var currency = '<?php echo $currencySymbol;?>';
								var auc_price = currency+""+finalProductPrice;
								console.log(productPrice);
								console.log(auc_price);
								document.getElementById("aPrice_" + productid).innerHTML = auc_price ;
								
								
							}

                                if (distance < 0) {
                                    clearInterval(x);
                                    document.getElementById("auction_days_" + productid).innerHTML = 0 + "d: ";
                                    document.getElementById("auction_hours_" + productid).innerHTML = 0 + "h: ";
                                    document.getElementById("auction_minutes_" + productid).innerHTML = 0 + "m: ";
                                    document.getElementById("auction_seconds_" + productid).innerHTML = 0 + "s ";

                                    $.ajax({
                                        type: 'POST',
                                        url: "<?php echo $this->getUrl('auction/startbid/start');?>",
                                        data: {remove: true},
                                        dataType: "json",
                                        success: function (res) {
                                            window.location.reload();
                                        }
                                    });
                                }
                            }, 1000);
                        }
                    });
                });
            </script>
            <?php
        }?>
    </ol>
    <?php if (count($auctionDetails->getData()) == 0) { ?>
        <div><p>Sorry, no auction products are available.</p></div>
    <?php } ?>
</div>


<?php if ($block->getPagerHtml()) { ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php
} ?>

<style>
div#countdown_timer {
    margin-top: 0;
    padding: 0;
}
.item.product.product-item {
    padding: 20px 4px!important;
}
.price-box {
    height: 38px;
    clear: both;
    padding-top: 0px;
	margin:0;
}
button.action.tocart.primary {
    background: #fff;
    font-weight: 500;
    color: #000;
    border: 1px solid #ddd;
    border-radius: 3px;
    box-shadow: 2px 2px 4px grey;
	  float: left;
    width: 45%;
	clear:both;
	line-height:25px;
	height:28px;
}
.secondary-addto-links.actions-secondary {
    position: absolute!Important;
    top: 0!important;
    right: -3px;
}
a.product-item-link {
    font-size: 12px;
    text-align: center;
    DISPLAY: block;
}
a.action.towishlist {
    border: none!important;
}
.item.product.product-item {
    border: 1px solid #ddd;
    border-radius: 7px;
    margin-right: 10px;
    max-width: 23%!important;
}
.item.product.product-item {
    padding: 10px 5PX!important;
}
.checkbox.related {
    display: none;
}
a.product.photo.product-item-photo {
    border: 0px solid #ddd;
}

.product-item .tocart:before
{
display:none;
}
img.product-image-photo {
    width: 165px;
    height: 165px;
    left: -10px;
}
.related-starting-bid {
    padding: 0px 0 10px 0px;
}
.product.actions.product-item-actions {
    margin: 0;
}
a.action.tocart.primary {
    height: 28px;
}
.related-starting-bid label {
    font-size: 12px;
}
.related-starting-bid span {
    font-size: 12px;
	font-weight:bold;
}
.products-grid .product-item-actions .tocart
{
display:block;
}
.action.towishlist span {
    display: none;
}
.product-item .action.towishlist:before {
    color: #ed4949;
}

.auc_price {
    font-size: large;
    margin-left: 10px;
    float: left;
}
.delivery-sec {
    margin: 0 0 -10px 0;
    border-top: 1px solid #ddd;
}
.products-grid .product-item .product-item-info {
    position: relative;
    display: inline-block;
    padding-bottom: 10px;
}
.products-grid .product-item .product-item-details {
    text-align: left;
    display: inline-block;
    width: 100%;
}
.start-price-box {
    height: 50px;
}
.delivery-sec img {
    width: 100%;
}
</style>



